name: Install pnpm
description: Install dependencies and pnpm cache

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        standalone: true
        run_install: false
        dest: ~/.pnpm

    - name: Cache pnpm-store
      uses: actions/cache@v3
      id: pnpm-store
      with:
        path: ${{ PNPM_HOME }}
        key: pnpm-store-${{ hashFiles('.npmrc') }}

    - name: Cache node_modules
      uses: actions/cache@v3
      id: node-modules
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Set publishing config
      run: pnpm config set '//npm.pkg.github.com/:_authToken' "${NODE_AUTH_TOKEN}"
      shell: bash

    - name: Install dependencies
      if: steps.node-modules.cache-hit != 'true'
      run: pnpm install --frozen-lockfile
      shell: bash
