name: Install pnpm
description: Install dependencies and pnpm cache

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        standalone: true
        run_install: false
        dest: /home/runner/.pnpm

    - name: Set pnpm store directory
      shell: bash
      run: echo "PNPM_HOME=.pnpm" >> $GITHUB_ENV

    - name: Check pnpm store directory
      shell: bash
      run: pnpm store path

    - name: Check pnpm home var
      shell: bash
      run: echo $PNPM_HOME

    - name: Cache pnpm-store
      uses: actions/cache@v3
      id: pnpm-store
      with:
        path: .pnpm-store
        key: pnpm-store-${{ hashFiles('.npmrc') }}

    - name: Cache node_modules
      uses: actions/cache@v3
      id: node-modules
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Set publishing config
      run: pnpm config set '//npm.pkg.github.com/:_authToken' "${NODE_AUTH_TOKEN}"
      shell: bash

    - name: Install dependencies
      if: steps.node-modules.cache-hit != 'true'
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Test /home/runner/
      run: ls -a /home/runner/
      shell: bash

    - name: Test /home/runner/.pnpm
      run: ls -a /home/runner/.pnpm
      shell: bash

    - name: Test /home/runner/.pnpm/node_modules
      run: ls -a /home/runner/.pnpm/node_modules
      shell: bash

    - name: Test /home/runner/.pnpm/node_modules/.bin
      run: ls -a /home/runner/.pnpm/node_modules/.bin
      shell: bash
