name: Packs cache update

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'release/**'
    paths:
      - 'pnpm-lock.yaml'

env:
  PNPM_HOME: ./.pnpm-store

jobs:
  create-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
