name: Publish
on:
  release:
    types: [published]

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - run: pnpm login
      - run: pnpm publish --no-git-checks --access public
