name: Release

on:
  push:
    branches:
      - main
      - 'release/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release-please
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node
      - run: echo ${{ steps.release-please.outputs.release_created }}
      - run: echo ${{ steps.release-please.outputs.tag_name }}
  validate:
    needs: release
    if: ${{ needs.release.outputs.release_created == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm test
